version: '3.1'

services:

  mongo: 
    image: mongo
    container_name : "mongo-service"
    ports:
      - 27017:27017
    expose : 
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 123456
      
  back: 
    container_name : "backend"
    build: ./backend
    depends_on: 
      - mongo
    ports:
      - 3000:3000


  front:
    container_name: "frontend"
    build: ./frontend
    ports:
      - 8080:8080   
    expose: 
      - 8080  
    
      